- name: Create code dirs
  file:
    path: "/home/{{ custom_username }}/{{ item }}"
    state: directory
    owner: "{{ custom_username }}"
    group: "{{ custom_username }}"
    mode: 0700
  with_items:
    - code/
    - code/src
    - code/src/DigitalOcean
    - code/src/VIC
    - code/src/danrabinowitz

# - git:
#     repo: git@github.internal.digitalocean.com:digitalocean/inbound-sendgrid.git
#     dest: "/home/{{ custom_username }}/code/src/DigitalOcean/inbound-sendgrid"
