- name: Create code dirs
  file:
    path: "/home/{{ custom_username }}/{{ item }}"
    state: directory
    owner: "{{ custom_username }}"
    group: "{{ custom_username }}"
    mode: 0700
  with_items:
    - code/
    - code/src
    - code/src/DigitalOcean
    - code/src/VIC
    - code/src/danrabinowitz
    - secrets
    - secrets/cisco
    - secrets/cisco/dev
    - secrets/cisco/dev/secrets

# - git:
#     repo: git@github.internal.digitalocean.com:digitalocean/inbound-sendgrid.git
#     dest: "/home/{{ custom_username }}/code/src/DigitalOcean/inbound-sendgrid"

# - name: Checkout foo repo
#   git:
#     repo: https://github.com/foo/bar.git
#     dest: "/home/{{ custom_username }}/code/src/foo/bar"
#   become: "{{ custom_username }}"


- name: "docker : Add apt key"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: "docker : Add repository"
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
    state: present
    filename: docker

- name: "docker : Install 'docker-ce' and supporting packages"
  apt:
    name: ['docker-ce', 'python-setuptools', 'python-pip']
    update_cache: yes
    install_recommends: no

# - name: "docker: Install pip packages"
#   pip:
#     name: docker

- name: "docker : Add users to the docker group"
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  with_items:
    - "{{ custom_username }}"

- name: Install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.24.0/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'
