- name: Install zsh
  apt:
    name: zsh
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Set custom_username to use zsh
  user:
    name: "{{ custom_username }}"
    shell: /bin/zsh

- name: Install diff-so-fancy
  copy:
    src: diff-so-fancy
    dest: /usr/local/bin/wtf
    remote_src: yes
    owner: root
    group: root
    mode: '0755'


- name: Checkout personal dotfiles repo
  git:
    repo: https://github.com/danrabinowitz/dotfiles.git
    dest: "/home/{{ custom_username }}/.dotfiles.git"
- name: Set ownership of dotfiles
  file:
    path: "/home/{{ custom_username }}/.dotfiles.git"
    state: directory
    recurse: yes
    owner: "{{ custom_username }}"
    group: "{{ custom_username }}"

- name: Create symbolic links for dotfiles
  file:
    src: ".dotfiles.git/dot.{{ item }}"
    dest: "/home/{{ custom_username }}/.{{ item }}"
    state: link
    force: yes
  with_items:
    - bash_profile
    - bashrc
    - dircolors
    - emacs
    - emacs.d
    - gitconfig
    - irbrc
    - profile
    - inputrc
    - tmux.conf
    - psqlrc
    - my.cnf
    - gitignore_global
