- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - zsh
    - direnv
    - zsh-syntax-highlighting

- name: Symlink zsh-syntax-highlighting
  file:
    src: "/usr/share/zsh-syntax-highlighting"
    dest: "/usr/local/share/zsh-syntax-highlighting"
    state: link

# git clone https://github.com/zsh-users/zsh-autosuggestions ~/.zsh/zsh-autosuggestions
- name: Install zsh-autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "/usr/local/share/zsh-autosuggestions"

- name: Set custom_username to use zsh
  user:
    name: "{{ custom_username }}"
    shell: /bin/zsh

- name: Install diff-so-fancy
  copy:
    src: "diff-so-fancy"
    dest: "/usr/local/bin/diff-so-fancy"
    owner: root
    group: root
    mode: '0755'


- name: Checkout personal dotfiles repo
  git:
    repo: https://github.com/danrabinowitz/dotfiles.git
    dest: "/home/{{ custom_username }}/.dotfiles.git"
- name: Set ownership of dotfiles
  file:
    path: "/home/{{ custom_username }}/.dotfiles.git"
    state: directory
    recurse: yes
    owner: "{{ custom_username }}"
    group: "{{ custom_username }}"

- name: Create .dotfiles
  file:
    src: ".dotfiles.git"
    dest: "/home/{{ custom_username }}/.dotfiles"
    state: link
- name: Create Config
  file:
    src: ".dotfiles.git"
    dest: "/home/{{ custom_username }}/Config"
    state: link

- name: Create symbolic links for dotfiles
  file:
    src: ".dotfiles.git/dot.{{ item }}"
    dest: "/home/{{ custom_username }}/.{{ item }}"
    state: link
    force: yes
  with_items:
    - bash_profile
    - bashrc
    - dircolors
    - emacs
    - emacs.d
    - gemrc
    - gitconfig
    - gitignore_global
    - inputrc
    - irbrc
    - my.cnf
    - profile
    - profile_interactive
    - psqlrc
    - railsrc
    - rspec
    - tmux.conf
    - tmux.conf.local
    - zshrc


- name: Install dot.profile_interactive_local
  copy:
    src: "dot.{{ item }}"
    dest: "/home/{{ custom_username }}/.{{ item }}"
    owner: "{{ custom_username }}"
    group: "{{ custom_username }}"
    mode: '0400'
  with_items:
    - profile_interactive_local
    - zshenv

- name: Install devenv-tips.txt
  copy:
    src: "devenv-tips.txt"
    dest: "/home/{{ custom_username }}/devenv-tips.txt"
    owner: "{{ custom_username }}"
    group: "{{ custom_username }}"
    mode: '0400'

# Jump
# https://github.com/gsamokovarov/jump/releases/download/v0.23.0/jump_0.23.0_amd64.deb
- name: Check if jump is installed
  command: dpkg-query -W jump
  register: jump_check_deb
  failed_when: jump_check_deb.rc > 1
  changed_when: jump_check_deb.rc == 1

- copy:
    src: "jump_0.23.0_amd64.deb"
    dest: "/var/tmp/jump.deb"
    owner: root
    group: root
    mode: 0400
  when: jump_check_deb.rc == 1

- name: Install jump
  apt:
    deb: "/var/tmp/jump.deb"
  when: jump_check_deb.rc == 1

- name: Install Cisco dev secrets
  copy:
    src: cisco/dev.secrets.env
    dest: "/home/{{ custom_username }}/secrets/cisco/dev/secrets/env"
    owner: "{{ custom_username }}"
    group: "{{ custom_username }}"
    mode: 0400
