- name: Install zsh
  apt:
    name: zsh
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Set custom_username to use zsh
  user:
    name: "{{ custom_username }}"
    shell: /bin/zsh

- name: Checkout personal dotfiles repo
  git:
    repo: https://github.com/danrabinowitz/dotfiles.git
    dest: "/home/{{ custom_username }}/.dotfiles.git"

- name: Create symbolic links for dotfiles
  file:
    src: ".dotfiles.git/dot.dircolors"
    dest: "/home/{{ custom_username }}/.dircolors"
    state: link



# create_symlink_for_dotfiles_git 'bash_profile'
# create_symlink_for_dotfiles_git 'bashrc'
# create_symlink_for_dotfiles_git 'dircolors'
# create_symlink_for_dotfiles_git 'emacs'
# create_symlink_for_dotfiles_git 'emacs.d'
# create_symlink_for_dotfiles_git 'gitconfig'
# create_symlink_for_dotfiles_git 'irbrc'
# create_symlink_for_dotfiles_git 'profile'
# #create_symlink_for_dotfiles_git 'screenrc'
# create_symlink_for_dotfiles_git 'inputrc'
# create_symlink_for_dotfiles_git 'tmux.conf'
# create_symlink_for_dotfiles_git 'psqlrc'
# create_symlink_for_dotfiles_git 'my.cnf'
# create_symlink_for_dotfiles_git 'gitignore_global'
